# Generated by Django 5.1.6 on 2025-03-14 11:54
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations

from posts.models import Post


def set_permissions(apps, schema_editor):
    user_group = Group.objects.get(name='user')
    moderator_group = Group.objects.get(name='moderator')

    content_type = ContentType.objects.get_for_model(Post)
    add_post_permission = Permission.objects.get(codename='add_post', content_type=content_type)
    change_post_permission = Permission.objects.get(codename='change_post', content_type=content_type)
    view_post_permission = Permission.objects.get(codename='view_post', content_type=content_type)
    delete_post_permission = Permission.objects.get(codename='delete_post', content_type=content_type)

    user_group.permissions.add(add_post_permission)
    user_group.permissions.add(change_post_permission)
    user_group.permissions.add(view_post_permission)
    user_group.permissions.add(delete_post_permission)

    moderator_group.permissions.add(view_post_permission)


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_permissions),
    ]
