services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: ./entrypoint.sh
    volumes:
      - .:/code
    depends_on:
      - db
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /code
        - action: rebuild
          path: package.json
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: