# Generated by Django 5.1.6 on 2025-03-14 10:34
from django.contrib.auth.models import Group
from django.db import migrations


def create_groups(apps, schema_editor):
    Group.objects.get_or_create(name='user')
    Group.objects.get_or_create(name='moderator')


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]


