# Generated by Django 5.1.6 on 2025-03-19 10:37
from django.contrib.auth import get_user_model
from django.db import migrations

from core.models import Profile


def fill_profiles(apps, schema_editor):
    users = get_user_model()
    for user in users.objects.all():
        if Profile.objects.filter(user__id=user.id).exists():
            continue
        else:
            Profile.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(fill_profiles)
    ]
