# Generated by Django 5.1.6 on 2025-04-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_created_by_alter_chat_participant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
