name: build and push image to docker hub

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  [workflow_dispatch]

jobs:

  publish_images:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: build image
      run: docker build ./ -t podpack/djangobackend-web:latest
    - name: push docker image
      run:
        echo ${{ secrets.DOCKER_HUB_TOKEN }}
        docker login -u podpack -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push podpack/djangobackend-web:latest
